#!/usr/bin/env python

"""
Create a number of games states and save them as JSON.

Used for easy development of the UI.
"""

from raottt.player.computer import ComputerPlayer
from raottt.game import opponent
import play
import random
import json



def main():
    """ """
    games = []
    blue = ComputerPlayer('Blue', opponent)
    red = ComputerPlayer('Red', opponent)

    for i in xrange(10):
        print('Playing game #%s' % i)
        game = play.run_game(blue, red, random.randint(6, 12), show=False)
        games.append(game.dump())

    with open('games.json', 'w') as ofile:
        ofile.write(json.dumps(games))


if __name__ == '__main__':
    main()
